name: Close Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ${{ vars.RUNS_ON }}
    permissions:
      issues: write
    steps:
      - uses: actions/stale@${{ vars.ACTION_STALE_VERSION }}
        with:
          only-issues: true
          days-before-stale: ${{ vars.STALE_DAYS_BEFORE_STALE }}
          days-before-close: ${{ vars.STALE_DAYS_BEFORE_CLOSE }}
          stale-issue-message: 'This issue is stale because it has been open ${{ vars.STALE_DAYS_BEFORE_STALE }} days with no activity. Remove "stale" label or comment or this will be closed in ${{ vars.STALE_DAYS_BEFORE_CLOSE }} days.'
          close-issue-message: 'This issue was closed because it has been stalled for ${{ vars.STALE_DAYS_BEFORE_CLOSE }} days with no activity.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security'
