name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ vars.RUNS_ON }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@${{ vars.ACTION_CHECKOUT_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@${{ vars.ACTION_SETUP_NODE_VERSION }}
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Test
        run: npm run test

      - name: Upload trace logs
        uses: actions/upload-artifact@${{ vars.ACTION_UPLOAD_ARTIFACT_VERSION }}
        with:
          name: accuracy-trace-logs
          path: analysis/
          if-no-files-found: error
